### PR TITLE
Huafangj @josere

### PR DESCRIPTION
**Pull request by huafangji**
Add Documents for Delivery Groups APIs.
The new structure is agreed between IX team, Architect and Development team.

### CODE REVIEW

**Comment by josere** [comment]
@huafangji We found spelling errors in the build.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'machinecatalogs'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'appdisks'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'appgroups'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'customerid'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'xendesktop'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'api'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'ui'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'http'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'customerid'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'xendesktop'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'api'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'Uid'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'Uuid'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'DesktopsAndApps'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'Apps'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'Uid'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'Uid'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'Uuid'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'DesktopsAndApps'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'AppsOnly'.
[Error] [DevPortalSpellCheck.Main] File 'delivery_groups_api.html' contains misspelled word 'multitenant'.

**Comment by josere** [comment]
@srad123 let's fix the spelling errors first. Then we will be able to see it at https://devportalbvt.ctxwsdev.net/.

**Comment by huafangji** [comment]
Hi, @josere @srad123 @felipelcc Thanks for all your reviewing. For these spelling errors, they are part of the Url or Request/Response properties, so they cannot be fixed.

**Comment by josere** [comment]
@huafangji they need to be fixed. Either change then to use pascal/camel case or add them to the SpellCheckIgnoreList.json.

**Comment by huafangji** [comment]
@josere ok, got it, thanks! I have fixed the spelling errors. Which tool do you used for the spelling check?

Another question is about the release of the document. After my code is merged into develop, when will it be available on the https://developer.cloud.com/ site?
Thanks a lot!

**Comment by josere** [comment]
@huafangji spell checking occurs during deployment. we have a Jenkins job at https://csg-dev.eng.citrite.net/job/devportal/job/csg-devportal/ that can build from github branch and deploy into bvt subscription. I just started a job to verify.

We have other projects in Jenkins to:
1. Check for changes in develop branch in github and deploy to developer.cloudburrito.com.
2. Wait two days and then merge from develop to master branch.
3. Check for changes in master branch in github and deploy to developer.cloud.com.
All this info is already at https://info.citrite.net/pages/viewpage.action?pageId=1267709913

**Comment by josere** [comment]
@huafangji not sure what got fixed. We are still seeing errors:
[Error] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'machinecatalogs'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'appdisks'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'appgroups'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'customerid'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'xendesktop'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'api'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'ui'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'http'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'customerid'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'xendesktop'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'api'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'deliverygroups'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'Uid'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'Uuid'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'DesktopsAndApps'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'Apps'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'Uid'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'Uid'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'Uuid'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'DesktopsAndApps'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'AppsOnly'.
[Error] File 'delivery_groups_api.html' contains misspelled word 'multitenant'.

**Comment by huafangji** [comment]
@josere Please hold merge develop to master, as info I get, the delivery groups APIs need wait the XAXD cloud58 before announcing it to Customer. Is that ok?

**Pull request merged**
